#!/usr/bin/env python3

import argparse, glob, os, os.path, platform, sys

parser = argparse.ArgumentParser(description = '''remove temporary files in given directory''')
parser.add_argument(
  '-w',
  '--workdir',
  default = '../data/junioreditor',
  help = 'working directory relative to program directory, the default is ../data/junioreditor'
)
parser.add_argument(
'-p',
'--pdf',
action = 'store_true',
help = 'include autogenerated-*.pdf and test-*.pdf'
)
parser.add_argument(
  '-t',
  '--tex',
  action = 'store_true',
  help = 'include autogenerated-*.tex, but not test-*.tex'
)
args = parser.parse_args()
progdir = os.path.dirname(os.path.realpath(__file__))
workdir = os.path.join(progdir, args.workdir)

os.chdir(workdir)
print('tidying up')

endings = ['aux', 'bib', 'bbl', 'blg', 'log', 'out',]
if args.pdf:
  endings.append('pdf')
if args.tex:
  endings.append('tex')
for ending in endings:
  files = glob.glob('autogenerated-*.' + ending)
  if ending != 'tex':
    files.extend(glob.glob('test-*.' + ending))
  for f in files:
    try:
      os.remove(f)
    except OSError:
      print(f"Error while deleting file '{f}'")

f = 'doc_data.txt'
if os.path.exists(f):
  try:
    os.remove(f)
  except OSError:
    print(f"Error while deleting file '{f}'")
